### ISSUE TITLE
Add support for specifying more than just the number of minutes like "4pm to 6pm" or "1 hour"

### ISSUE THREAD

**Issue by RohitRajendran** [RohitRajendran/bumblebee#129]
Currently Bumblebee only supports specifying a number of minutes to be active for. Let's add support for specifying more than just the number of minutes like "4pm to 6pm" or "1 hour".

Example messages to be able to parse:

- [x] "30" - Active from now to 30 minutes from now (this is what is currently implemented)
- [ ] "4pm to 6:30pm" - Active from 4pm to 6:30pm of current day if current time is before 4pm, otherwise next day 4pm to 6:30pm.
- [ ] "4pm to 6:30pm on Oct 17" - Active from 4pm to 6:30pm of Oct 17th
- [ ] "6pm" - Active until 6pm of current day if current time is before 4pm, otherwise next day 6pm
- [ ] "2 hours" - Active for the next 2 hours

**Comment by vijayakshit** [comment]
@RohitRajendran https://github.com/RohitRajendran/bumblebee/pull/139
Had some question regarding this.
1. I'm assuming your DB is a json store so addition of a new field wont need any schema changes.
2. Have Outlined Possible changes to get this functionality working. If it seems good, I can start working on the same.

**Comment by RohitRajendran** [comment]
@vijayakshit Thanks for taking a look into this!

1. Yup, no schema changes will be needed.
1. Overall looks about right! Just keep in mind that it should be able to continue to support just passing in the number of minutes like it currently does and be flexible to support various different types of message in the future. Some thoughts on the different types of message and how it'll eventually support and how it would handle it:

"30" - Active from now to 30 minutes from now (this is what is currently implemented)
"4pm to 6:30pm" - Active from 4pm to 6:30pm of current day if current time is before 4pm, otherwise next day 4pm to 6:30pm.
"6pm" - Active until 6pm of current day if current time is before 4pm, otherwise next day 6pm
"2 hours" - Active for the next 2 hours

Appreciate the help!

**Comment by vijayakshit** [comment]
The explanation really helps, Yes will handle these scenarios . Could you assign this issue to me?
